import { useEffect, useState } from 'react'
import { supabase } from '../lib/supabaseClient'
import { useRouter } from 'next/router'

export default function Dashboard() {
  const [user, setUser] = useState(null)
  const [loading, setLoading] = useState(true)
  const router = useRouter()

  useEffect(() => {
    // Get current session/user
    async function getUser() {
      const { data: { session } } = await supabase.auth.getSession()
      if (session?.user) {
        setUser(session.user)
      } else {
        router.push('/login') // redirect back if not logged in
      }
      setLoading(false)
    }

    getUser()

    // Listen for auth state changes (login/logout)
    const { data: listener } = supabase.auth.onAuthStateChange(
      async (_event, session) => {
        if (session?.user) setUser(session.user)
        else router.push('/login')
      }
    )

    return () => {
      listener.subscription?.unsubscribe()
    }
  }, [router])

  if (loading) return <p className="text-center mt-20">Loading...</p>

  return (
    <main className="min-h-screen bg-gray-50 font-poppins">
      <header className="bg-white py-4 px-8 shadow-md flex justify-between items-center">
        <h1 className="text-xl font-bold text-[#1877F2]">WorkfluxAI Dashboard</h1>
        <button
          className="bg-red-500 text-white px-4 py-2 rounded"
          onClick={async () => {
            await supabase.auth.signOut()
            router.push('/login')
          }}
        >
          Logout
        </button>
      </header>

      <section className="px-8 py-12">
        <h2 className="text-2xl font-bold mb-4">👋 Welcome back, {user?.email}</h2>
        <p className="text-gray-600 mb-8">
          Here’s where you’ll soon see your connected tools, automated reports, and subscription status.
        </p>

        {/* Placeholder cards */}
        <div className="grid md:grid-cols-3 gap-6">
          <div className="p-6 bg-white rounded shadow hover:shadow-lg">
            <h3 className="font-semibold mb-2">Connected Tools</h3>
            <p>Slack + Jira integration status.</p>
          </div>

          <div className="p-6 bg-white rounded shadow hover:shadow-lg">
            <h3 className="font-semibold mb-2">Reports</h3>
            <p>Latest weekly client reports generated by AI.</p>
          </div>

          <div className="p-6 bg-white rounded shadow hover:shadow-lg">
            <h3 className="font-semibold mb-2">Billing</h3>
            <p>Current plan: <span className="font-bold text-[#1877F2]">Starter</span></p>
          </div>
        </div>
      </section>
    </main>
  )
}